BEGIN;

CREATE TABLE public.jwt_tokens (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   token VARCHAR NOT NULL,
                                   token_type VARCHAR NOT NULL,
                                   expired BOOLEAN NOT NULL,
                                   revoked BOOLEAN NOT NULL,
                                   user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE
);

COMMIT;