-- V1__create_schema.sql
BEGIN;

CREATE TABLE car_producent (
                                id bigint generated by default as identity primary key,
                                name VARCHAR(255) NOT NULL
);

CREATE TABLE colors (
                       id bigint generated by default as identity primary key,
                       name VARCHAR(255) NOT NULL
);

CREATE TABLE petrols (
                        id bigint generated by default as identity primary key,
                        name VARCHAR(255) NOT NULL
);

CREATE TABLE cars (
                       id bigint generated by default as identity primary key,
                       name VARCHAR(255) NOT NULL,
                       mark_id BIGINT,                -- FK -> car_producent
                       price BIGINT,
                       description TEXT,
                       color_id BIGINT,               -- FK -> color
                       mileage BIGINT,
                       car_status VARCHAR(255),
                       petrol_type_id BIGINT,         -- FK -> petrol
                       engine_capacity INTEGER,
                       power INTEGER,
                       photos_url TEXT,
                       year INTEGER,
                       CONSTRAINT fk_cars_mark FOREIGN KEY (mark_id) REFERENCES car_producent (id) ON DELETE SET NULL,
                       CONSTRAINT fk_cars_color FOREIGN KEY (color_id) REFERENCES colors (id) ON DELETE SET NULL,
                       CONSTRAINT fk_cars_petrol FOREIGN KEY (petrol_type_id) REFERENCES petrols (id) ON DELETE SET NULL
);

CREATE INDEX idx_cars_mark_id ON cars(mark_id);
CREATE INDEX idx_cars_color_id ON cars(color_id);
CREATE INDEX idx_cars_petrol_type_id ON cars(petrol_type_id);

COMMIT;
