-- V3__add_user_table.sql
CREATE TABLE users (
                      id bigint generated by default as identity primary key,
                      username VARCHAR(255) NOT NULL,
                      email VARCHAR(320) UNIQUE NOT NULL,
                      password TEXT NOT NULL
);