-- V8__add_relation_between_cars_and_profiles.sql
BEGIN;

DROP TABLE IF EXISTS public.users_profiles CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE users (
                       id bigint generated by default as identity primary key,
                       username VARCHAR(255) NOT NULL,
                       email VARCHAR(32) NOT NULL UNIQUE,
                       password TEXT NOT NULL
);

CREATE TABLE users_profiles (
                                id bigint generated by default as identity primary key,
                                user_id BIGINT NOT NULL UNIQUE,
                                CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE public.users_profiles
    ADD COLUMN rating DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE public.users_profiles
    ADD COLUMN rating_count INT DEFAULT 0;

ALTER TABLE public.cars
    ADD COLUMN users_profiles_id BIGINT;

INSERT INTO public.users (username, email, password)
    VALUES ('Admin', 'admin@exmaple.com', 'admin123');

INSERT INTO public.users_profiles (user_id)
    VALUES ((SELECT id FROM public.users LIMIT 1));

UPDATE public.cars SET users_profiles_id = 1 WHERE users_profiles_id IS NULL;

ALTER TABLE public.cars
    ADD CONSTRAINT fk_car_owner
        FOREIGN KEY (users_profiles_id) REFERENCES users_profiles(id) ON DELETE CASCADE;

ALTER TABLE public.cars
    ALTER COLUMN users_profiles_id SET NOT NULL;

COMMIT;