-- V9_email_verification.sql
BEGIN;

ALTER TABLE public.users
    DROP COLUMN username;

ALTER TABLE public.users_profiles
    ADD COLUMN profile_name VARCHAR(255) NOT NULL DEFAULT 'User';

ALTER TABLE public.users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE email_verification_token(
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         user_id BIGINT NOT NULL UNIQUE,
                                         token VARCHAR(6) NOT NULL,
                                         expires_at TIMESTAMP NOT NULL,
                                         CONSTRAINT fk_profiles_user
                                             FOREIGN KEY (user_id)
                                                 REFERENCES public.users(id)
                                                 ON DELETE CASCADE
);


COMMIT;
